data:
  type: cifar10
  train_dir: data/CIFAR
  img_size: 32
  nlabels: 10
generator:
  name: dcgan_deep
  nlabels: 1
  conditioning: unconditional
  kwargs:
    placeholder: None
discriminator:
  name: dcgan_deep
  nlabels: 1
  conditioning: unconditional
  kwargs:
    placeholder: None
z_dist:
  type: gauss
  dim: 128
clusterer:
  name: supervised
  nimgs: 25000
  kwargs: 
    placeholder: None
training:
  gan_type: standard
  reg_type: none
  reg_param: 0.
  take_model_average: false
  sample_nlabels: 20
  log_every: 1000
  inception_every: 10000
  batch_size: 64