data:
  type: lsun
  train_dir: data/LSUN
  deterministic: False
  img_size: 128
  nlabels: 1
generator:
  name: resnet
  nlabels: 1
  conditioning: unconditional
  kwargs: 
    placeholder: None
discriminator:
  name: resnet
  nlabels: 1
  conditioning: unconditional
  kwargs: 
    pack_size: 1
    placeholder: None
clusterer:
  name: supervised
  nimgs: 100
  kwargs: 
    num_components: -1
z_dist:
  type: gauss
  dim: 256
training:
  out_dir: output/default
  gan_type: standard
  reg_type: real
  reg_param: 10.
  log_every: 1
  batch_size: 128
  ntest: 128
  nworkers: 72
  burnin_time: 0
  take_model_average: true
  model_average_beta: 0.999
  monitoring: tensorboard
  sample_every: 5000
  sample_nlabels: 20
  inception_every: 10000
  inception_nsamples: 50000
  backup_every: 10000
  recluster_every: 10000
  optimizer: adam
  lr_g: 0.0001
  lr_d: 0.0001
  beta1: 0.0
  beta2: 0.99
pretrained: {}